receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  otlphttp:
    endpoint: http://adapter:8001/otlp

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
